### ISSUE TITLE
Question / Request: Change domain for HTTPS

### ISSUE THREAD

**Issue by JosieBigler** [httptoolkit/mockttp#105]
I would like the ability to change the domain on the generated Cert when using HTTPS.  Right now it looks like it's defaulting to `localhost`. https://github.com/httptoolkit/mockttp/blob/10cbfa3f835afda9e978374bc7d558d36d1f4b1e/src/server/http-combo-server.ts#L156   

My setup is really bare bones: 

```
(async () => {
    const mockttp = require('mockttp');

    const server = mockttp.getLocal({
        https: {
            keyPath: './testKey.pem',
            certPath: './testCert.pem'
        }
    });

    server.forAnyRequest()
        .thenForwardTo("{myUrl}");

    await server.start();

    console.log(`Server running on port ${server.port}`);
    
})(); 
``` 

However, despite how I configure my CA and cert in the https options, I still get a commonName of `localhost` from the mockttp `generateCertificate()`

**Comment by pimterry** [comment]
Hi @JosieBigler, I'm not sure from this or #106 what exactly is happening here. The default certificate that that PR changes is only used when the client doesn't use [SNI](https://en.wikipedia.org/wiki/Server_Name_Indication), which is _very_ rare for normal requests - it's really only relevant to super old clients (pre-2005), raw TLS connections, or requests made directly to IP addresses instead of hostnames. In each case there's probably a better solution.

For all requests that do use SNI, that `localhost` default value isn't used at all - instead the `SNICallback` (just below) is called with the name given by the client, and the certificate is dynamically generated to match the name the client asked for.

Can you explain what requests you're sending and how? I'm happy to change this default if it does help your use case, but we'd definitely need a new test covering that use case explicitly, and I suspect right now the change in that PR doesn't actually fix your issue.

**Comment by JosieBigler** [comment]
Hi @pimterry .  I'm not exactly sure what's going on.  I'm tasked with integrating a proprietary, rather old client.  I can configure the client to route through a proxy, and my options are an IP address/ Hostname, and a Port.  

I've tested the changes this morning, and when I can configure the domain, I can get a connection, otherwise I get an error saying `localhost is not a known host`. 

Of the three options you listed (pre-2005 client, raw TLS, direct IP), I think it must be a raw TLS connection? As we're able to resolve a DNS name with the proxy. I don't know exactly when the client's software was written, but I don't think it's older than 2005. 

I am interested in different solutions. I have tried a handful of other proxy'ing libraries and none of them work.  

The team I'm working with previously used Squid successfully (but has since lost the knowledge of how it worked). I'd prefer some solution with `mockttp` as it's much simpler and easier to configure.
