### ISSUE TITLE
Mockttp is not working with Node.js 19 / Wrong connection header handling

### ISSUE THREAD

**Issue by freaz** [httptoolkit/mockttp#107]
I ran into issue with mockttp after updating to Node.js 19.

Unfortunately, I couldn't figure out what is the root cause and prepare replication. I assume it is related to updated [llhttp](https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V19.md#llhttp-810) or [keepalive by default](https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V19.md#https11-keepalive-by-default).

Here is fork with Node.js 19 in testing matrix which is failing:
https://github.com/freaz/mockttp/actions/runs/3395295030/jobs/5644990838

**Comment by freaz** [comment]
After looking into failing tests, they are really just about default keepalive header. The issue I have is that mockttp doesn't receive all calls it is supposed. So, I need to really find replication for it.

**Comment by pimterry** [comment]
Hi @freaz, yes, I think you're right - most errors there are just because Mockttp's tests assume that Node.js doesn't use keep-alive by default. That's just an issue with the tests, not the library in general, but yes it would be good to fix that.

If you have a minute, a PR would be very welcome! We already have various cases in the tests for [other differences](https://github.com/httptoolkit/mockttp/blob/432fcc0a57caa3c5cc8b7ef1ff4b05078abe0196/test/test-utils.ts#L230-L234) between node versions, and I think we can probably do the same here (i.e. add a new constant, and change the assert in the tests to check `process.version` and look for different headers depending on the node version).

I haven't looked into Node 19 much for Mockttp yet. I suspect there'll be some other differences in here too, but as far as I'm aware there's nothing that would break real functionality, just low-level assumptions within in our own test suite.

**Comment by pimterry** [comment]
I did some digging, and I'm fairly sure this is a Node bug. I've filed an issue here: https://github.com/nodejs/node/issues/46321. They seem to broadly agree, and I've opened a PR that should fix this in future.

The underlying problem: although we're removing the Connection header (because `thenJson` automatically defines some response headers, and doesn't specify a Connection header there) that shouldn't matter, because for HTTP/1.1+ keep-alive is the default anyway. The reason the client is failing is because it's expecting the connection to be kept alive, but Node's HTTP implementation incorrectly automatically kills connections after responses if you remove the Connection header.

What should actually happen is that Node should try to keep the connection alive, even if you remove the header, unless you explicitly send a "Connection: close" header. If it did that, then Mockttp would work correctly here. The PR to fix that is here: https://github.com/nodejs/node/pull/46331

Fortunately, it looks like we may well be able to get this fixed in Node, which would resolve this long term. In the short term, I'm going to quickly patch this in Mockttp too, by adding an explicit 'Connection: keep-alive' header to the default headers set for `thenJson` responses, to ensure Node behaves correctly in that case. In future we might be able to limit that to only affected Node versions, but for now we'll just set it everywhere.

**Comment by pimterry** [comment]
This has now been released in Mockttp v3.6.3: `thenJson` will now automatically set the keep-alive header, and so Node will correctly keep the connection alive as expected.

In addition, the Node team have merged my PR there too. Once that's shipped (in the next major release, i.e. Node v20 in April) then this should work in new Node, even with older Mockttp releases. Once that's live I'll retest and add a check to skip that header again in versions of Node where it's not required.

Thanks for reporting this! Great to be able to fix it here _and_ fix node long-term for everybody else :+1:

**Comment by freaz** [comment]
@pimterry thank you so much for your work. 🙏
