### ISSUE TITLE
Is there a regular match to the local directory

### ISSUE THREAD

**Issue by name-q** [httptoolkit/mockttp#112]
I want to achieve：
server.forGet(/xxx\\/*/)
            .thenDirectory('/Users/qy/Documents/xxx') //Only thenFromFile() was found

api  /xxx/a.js
       /xxx/a.css
       /xxx/c.json
Will go to the local directory: /Users/qy/Documents/xxx

**Comment by name-q** [comment]
Implemented with thenCallback. This library is very powerful

**Comment by pimterry** [comment]
As you discovered, no, that doesn't exist right now, but yes I think `thenCallback` is the right workaround :smile:

If you're especially interested though, I'm open to a PR to add first-class support for this. It's a little tricky because the handlers (`thenX`) can't access data from the matchers (`forY`) - they're totally independent. That said, there's probably some interesting approaches available to make this work anyway, feel free to investigate if you're keen.
