### ISSUE TITLE
Cancel outgoing request when invoking `Mockttp.stop()`

### ISSUE THREAD

**Issue by pmdartus** [httptoolkit/mockttp#116]
First of all, thanks for sharing this amazing project.

I am currently working on a network record and replay and I am evaluating using mockttp for this project. One of the applications that I am testing against is using long polling. 

Calling `Mockttp.stop()` close all the incoming connections to the proxy server, but doesn't close the outgoing ones. And the open connection created by the long polling request prevents the Node.js process from exiting properly. The current workaround that I am using is to run mockttp within a worker thread and kill the worker when the recording is done, which isn't ideal.

This would likely require passing around a signal to the request handlers to cancel the pending requests. Any thoughts about this before I start working on a PR?

**Comment by pimterry** [comment]
Hi @pmdartus, thanks for this, that's an interesting find.

I think in general, rather than needing to pass & track a separate signal, handlers should listen for the request itself to be closed, and then propagate that - i.e. disposing upstream connections or doing any other cleanup. Then `stop()` just needs to close all client connections and everything upstream will be handled automatically, and that ensures that both full server shutdown and individual client disconnections are cleaned up the same way, which seems like a good goal.

I think [this code](https://github.com/httptoolkit/mockttp/blob/main/src/rules/requests/request-handlers.ts#L964-L971) should actually be handling that already, so it looks like this is a bug there, or at least a missing case that stops this handling connection shutdown.

If you're interested in this, do you want to look into that?

**Comment by pmdartus** [comment]
> If you're interested in this, do you want to look into that?
Yes, I will try to take a stab at it this week, to get myself familiarized with the codebase. I will let you know if I need help. 😉

**Comment by pmdartus** [comment]
I would be interested to start incorporating this change into my project. Are you planning to cut a new release any time soon? 

Again thanks for this great project.
