### ISSUE TITLE
Mechanism for using `ignoreHostCertificateErrors` with all domains

### ISSUE THREAD

**Issue by ashishmadeti** [httptoolkit/mockttp#128]
I am building a proxy server using mockttp. Is there a way where I can use `ignoreHostCertificateErrors` with each and every domain the request is coming for?

Something like `ignoreHostCertificateErrors: true` (instead of an array) or a function that returns array, like it happens for `proxyConfig`?

**Comment by pimterry** [comment]
Disabling certificate checks for all cases like this is usually a very bad idea, since it completely breaks all security protections for anybody using the proxy.

Can you explain more about your use case, and why you want to do this?

If you're trying to use an upstream proxy that is doing its own HTTPS interception for traffic to all domains, you probably want to use `extraCACertificates` and specifically trust that CA's certificate instead, which will allow that proxy (and _only_ that proxy) to intercept HTTPS to all domains.

**Comment by ashishmadeti** [comment]
I do understand the risks.

I am trying to proxy to a lot of sites (some internal), which have self-signed or expired certificates. So, I wanted to disable SSL verification completely for the proxied requests, for all hosts.

**Comment by pimterry** [comment]
Hmmmmmmm, I see. I'm cautious, but I can see the use case.

If you're interested, I'm open to PRs for this, to add `true` to the valid options. There are other solutions (regexes, callbacks) too, but they'd be quite a bit more complicated, and I think we can probably leave that until somebody has a specific need for it (although a PR would be welcome for those instead if that would be better for you).

If you add that, documentation in the [options type](https://github.com/httptoolkit/mockttp/blob/8ff6c167bd3bb860fe2e0115f475c0eb05c6725b/src/rules/requests/request-handler-definitions.ts#L487-L491) to cover this and make it clear that this has security risks would be helpful. You should be able to extend the tests to cover this easily, those are [here](https://github.com/httptoolkit/mockttp/blob/8ff6c167bd3bb860fe2e0115f475c0eb05c6725b/test/integration/proxying/https-proxying.spec.ts#L161-L189). The same change also needs to be applied for websockets, which have very similar logic for the same option [here](https://github.com/httptoolkit/mockttp/blob/8ff6c167bd3bb860fe2e0115f475c0eb05c6725b/src/rules/websockets/websocket-handlers.ts#L316-L317). Happy to give you more pointers if you have any questions at all :smile:
