### ISSUE TITLE
Cannot setup mockttp with karma for browser tests

### ISSUE THREAD

**Issue by rotemso** [httptoolkit/mockttp#23]
Hi,
I'm trying to setup mockttp with karma for browser tests as you suggested in your documentation:
mockttp -c karma start

With that, my test fails due to error:
 Error: Not connected to mock server
            at MockttpClient.<anonymous>

I guess that the standalone server is not ready when the local mock server is trying to connect to it...

Another interesting thing is that when running karma for debug (mockttp -c karma start -single-run=false) I see the same error in browser console, but after refreshing the browser window (after setting a breakpoint for example), I don't get to the karma debug page and instead I get a message that no rule is defined for debug.html request (which I guess that is coming from the mock server)...

After closing the browser tab and killing the process it got even worse when running "mockttp -c karma start" again, now I get another error:
events.js:183
      throw er; // Unhandled 'error' event
      ^
Error: listen EADDRINUSE :::45456
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at Server.setupListenHandle [as _listen2] (net.js:1355:14)
    at listenInCluster (net.js:1396:12)
    at Server.listen (net.js:1480:7)
    at Function.listen (...\node_modules\express\lib\application.js:618:24)
    at ...\node_modules\mockttp\dist\standalone\mockttp-standalone.js:137:87
    at new Promise (<anonymous>)
    at MockttpStandalone.<anonymous> (...\node_modules\mockttp\dist\standalone\mockttp standalone.js:136:46)
    at step (...\node_modules\mockttp\dist\standalone\mockttp-standalone.js:35:23)

**My test code (TypeScript):**

```
import mockttp = require("mockttp");
describe("Client side integration tests from browser context", () => {
    const mockServer = mockttp.getLocal();
    beforeEach(() => {
        mockServer.start(9876);
    });
    afterEach(() => {
        mockServer.stop();
    });
.  .  .
});
```

Tried also defining mockServer outside the describe, with no luck...

**My karma.conf.js configuration:** 
```
module.exports = function(config) {
    config.set({
        frameworks: ["mocha", "karma-typescript"],
        autoWatch: false,
        singleRun: true,
        files: [
            "src/client/**/*.ts",
            "test/karma/**/*.spec.ts"
        ],
        preprocessors: {
            "**/*.ts": "karma-typescript"
        },
        karmaTypescriptConfig: {
            tsconfig: "./tsconfig.json"
        },
        reporters: ["progress", "karma-typescript"],
        browsers: ["Chrome"],
        port: 9876
    });
};
```

Can you please assist?
Would appreciate adding a section to your documentation with full setup details of mockttp and karma.

Thanks,
Rotem

**Comment by pimterry** [comment]
It should definitely be doable, this repo uses it for its own tests! `mockttp -c karma start` should be all you need.

The `Not connected to mock server` is the key problem here. This _doesn't_ mean the standalone server isn't ready (that is ready nearly instantly, well before karma opens your browser). It means you're trying to configure a mockttp server but you haven't started one yet.

I'm reasonably sure that error will be coming from the `mockServer.stop()` call being run before the `mockServer.start()` call finishes. You can avoid that by changing your beforeEach to wait on the returned promise:

```js
beforeEach(() => {
  return mockServer.start(9876); // Mocha will wait on returned promises
});
```

Otherwise everything in your code looks good to me.

The `EADDRINUSE` you're seeing means the port that mockttp uses for standalone servers is still in use, which almost certainly means that you haven't killed it successfully, so mockttp is still running in a node process somewhere.

Can you try that and let me know if it works for you?

**Comment by pimterry** [comment]
Oh, one other thing: you need to wait on the promise returned by `stop()` as well.

With only one test you'll be fine, but otherwise your 2nd test will start to fail because it'll run `start(9876)` and the previous server will still be running.

When I don't have any other setup code, I frequently collapse all this and use implicit arrow function returns, like so:

```js
beforeEach(() => mockServer.start());
afterEach(() => mockServer.stop());
```

**Comment by rotemso** [comment]
Hi @pimterry,
Thank you very much for your response!
Indeed the 'return' was the missing piece - thanks!
With that, now it seems that requests are not caught by the mock server...
I added a very simple test case to my test, to make sure it is not something with my code - and it still fails:

```
import mockttp = require("mockttp");
describe("Client side integration tests from browser context", () => {
    const mockServer = mockttp.getLocal();
    beforeEach(() => {
        return mockServer.start(9876);
    });
    afterEach(() => {
        return mockServer.stop();
    });
    it("sample test with mock", ()=> {
        return mockServer.get("/test/my/api").thenReply(200, "{}").then(() => {
            return window.fetch("test/my/api").then(response => {
                console.log("response url: " + response.url + " status: " + response.status);
                expect(response.ok).to.be.true;
            });
        });
    });
});
```
When running this I get the following:

Chrome 72.0.3626 (Windows 10.0.0): Executed 0 of 1 SUCCESS (0 secs / 0 secs)
LOG: 'response url: **http://localhost:9876/test/my/api** status: **404**'
Chrome 72.0.3626 (Windows 10.0.0) Client side integration tests from browser context sample test with mock FAILED
        AssertionError: expected false to be true
            at window.fetch.then.response (. . .)
Chrome 72.0.3626 (Windows 10.0.0): Executed 1 of 1 (1 FAILED)

Note that request was indeed sent from localhost:9876 (same port that mock server set with) but response was not mocked as expected. 

I have no option in my code to set the request URL from outside (this is of course a simplification of what I really want to test...) and the request is only sent as relative to browser URL.

Am I missing something again?

Thanks,
Rotem

**Comment by pimterry** [comment]
I see, ok. There's two things going on here.

The 1st issue is a bug: if you call `start(port)` in the browser with a port that's already in use, then `start` will appear to succeed but actually the standalone server will crash. The `start(9876)` call in your code should actually fail, because Karma is already using that port. You can't start a mock server on a port that's already in use. I believe I've [now fixed this](https://github.com/httptoolkit/mockttp/commit/5c1c317cabd1c51acfb68e8fee7df08d99de271b), so that it errors more clearly, and that'll be released soon. 

The 2nd issue is in your test setup here. Mockttp always works in one of two ways:

1. You send requests directly to the mock server, by configuring the target URL
2. You send requests to any URL you like, by using the mock server as a proxy

You're not trying to do either right now. Instead you're trying to send a request to the Karma server directly, and expecting Mockttp to somehow intercept it.

Using a real HTTP proxy in the traditional way is difficult in the browser with Karma, but there is an option using Karma's `proxies` & `urlRoot` configuration options instead (see https://karma-runner.github.io/3.0/config/configuration-file.html). Using those allows you to tell Karma to pass requests on to another server (your Mockttp server), and to move all Karma's own URLs into a separate path.

That should look something like this:

```js
// Add to your Karma config:
urlRoot: '/__karma__/',
proxies: {
    '/': 'http://localhost:8000/'
},
```

Now your tests will automatically run from `http://localhost:9876/__karma__/`, and if they make any requests to `http://localhost:9876/test/my/api`, then those will be forwarded to that path on localhost port 8000. The last step is just to make sure that that is where your Mockttp server is running:

```js
// In your test setup:
beforeEach(() => {
    return mockServer.start(8000); // Needs to match Karma config port
});

// Any relative requests should now go to Mockttp as expected.
```

I haven't thoroughly tested this myself! All of Mockttp's tests just reconfigure the URL, which is generally easier. I'd love to hear if it works well for you though, do let me know how it goes.

**Comment by pimterry** [comment]
@rotemso did you try out the above? Does it work for you?

**Comment by pimterry** [comment]
I'm going to assume this is now working for you, and close this.

If you or anybody else are still hitting this issue do feel free to ping here with more details, and I'll take another look.

**Comment by rotemso** [comment]
@pimterry sorry I didn't have the chance to test this as I now moved to test our nodejs code with the mockttp... promise to update once I'll have the chance! Thank you very much for your support.
