### ISSUE TITLE
Rule builder docs?

### ISSUE THREAD

**Issue by ErisDS** [httptoolkit/mockttp#32]
Are there any docs for how to use the rule builder?

Or is there a way to easily get mockhttp to respond 200 to multiple requests?

I’m looking to setup tests for functions that make multiple requests to multiple urls. 

Ideally I want to be able to assert that the request method and headers are correct.

**Comment by pimterry** [comment]
Hi! Yeah, right now there's not many docs, that is right right at the top of my todo list. I'm very happy to help though! What do you mean by 'multiple requests'? In general you should be able to create a rule to match something (all GET requests, all requests to a certain URL pattern, etc), and then reply using the 'automated fixed response' with a 200 response and whatever data you like, and that will reply to every request automatically as you describe. Is that what you're looking for, or something else?

**Comment by ErisDS** [comment]
Docs are hard 😬

I’m trying to write maintainable, sensible unit tests. I landed on this project because I can never get that test structure I want using nock.

The function I’m testing makes different requests based on options. The requests vary in terms of method (they aren’t all GET), the url & path they hit, and the headers they send. So they don’t really have a common thing.

The only thing I have that is known is the list of all possible urls that could be requested. 

The requests are gonna change over time, so from a maintenance perspective being able to come back and update just assertions, not change mocking code is the ideal.

The thing I don’t like is that tests timeout instead of error when the mocks need to change.

Do you think this is possible?

**Comment by ErisDS** [comment]
As a little more background, I've been using nock for various bits for ages and always felt it didn't quite suit my needs (although it's a great project, no disparagement intended). 

A couple of weeks ago, I had to write some unit tests in Ruby, which is all new to me. I ended up using [webmock](https://github.com/bblimke/webmock) and really liked it. You enabled it at the start of your tests and then it automatically throws an error for any request that doesn't have a stub. Absolute bonus that it outputs the stub code you need to add.

The main point is - once you turn it on, if you make a request that isn't handled in the tests, the tests immediately fail, which is perfect.

**Comment by pimterry** [comment]
Right, this all makes sense, thanks!

> The thing I don’t like is that tests timeout instead of error when the mocks need to change.

This shouldn't be true. If Mockttp ever receives a request that doesn't match any rule, it immediately replies with a 503 error response (and includes some stub code in the response body, just like webmock). See [sendUnmatchedRequestError](https://github.com/httptoolkit/mockttp/blob/5193231577b3744b953ec122c620b132ea4ee9a1/src/server/mockttp-server.ts#L337-L355).

If you're checking your response status codes at all, then that should throw an error and thereby stop your test sharpish. Do you have an example where that's not happening?

In theory you could even add a fallback matcher to match tests that match nothing and then call a callback of your own, and stop the tests explicitly there, but you generally shouldn't need to.

Otherwise, it's should be perfectly possible to do what you're trying to do. I'd typically write a test that looks something like this:

```js
beforeEach(async () => {
  await server.start();
});

it("should do X successfully", async () => {
  await server.get('/an-endpoint').thenReply(200, "a response", { header: 'value' });
  await server.post('/elsewhere').thenReply(200, "a response", { header: 'value' });
  // ... as many other mocks as you like, potentially combine them with
  // more general matchers where you can, or keep them all separate as here
  
  const result = await doX();
  expect(result).to...();

  // Given that doX rejects/throws if any requests fail, then this test will
  // cleanly fail any time the mocks required change.
});
```

Does that help? Happy to explain more or take a look at an example if that'd be useful.

**Comment by pimterry** [comment]
Ok I'm going to close this for now, but let me know if there's anything else I can do to help.
