### ISSUE TITLE
The RunKit example is broken

### ISSUE THREAD

**Issue by mvasin** [httptoolkit/mockttp#34]
The readme suggests to try mockttp on RunKit

> Want to play with this yourself? Try running a standalone version live on RunKit: https://npm.runkit.com/mockttp

When I go there and click "run", an error pops up:
```
Error: Cannot find module 'ws'
Require stack:
- /app/available_modules/1586791592000/mockttp/dist/server/websocket-handler.js
- /app/available_modules/1586791592000/mockttp/dist/server/mockttp-server.js
- /app/available_modules/1586791592000/mockttp/dist/main.js
- /app/index.js
```

**Comment by pimterry** [comment]
I see, thanks for letting me know. I'm fairly sure this is a runkit issue, since Mockttp does depend on `ws` (though transitively, which should probably be made direct), and this does all work fine when installed normally. Runkit was certainly working fine until quite recently.

They seem to have issues at times (in many cases, unrelated to mockttp) where dependencies don't resolve correctly. I'll ping their support and ask them to take a look at it. Thanks!

**Comment by pimterry** [comment]
Took a little while, but this is now fixed! Thanks for the report :+1:
