### ISSUE TITLE
Question: Can mockhttp be used to intercept traffic and respond with a mock?

### ISSUE THREAD

**Issue by Cosmin-Gramada** [httptoolkit/mockttp#40]
Hi,

In our case, for every set of tests ran in the CI a new environment is created and made available for testing.
This means that the front-end client is already up-and-running and available when the integration tests are starting.

Having this in mind, would it be possible to use mockhttp to intercept the requests sent and respond with a mock instead of having the request go to the server?

In my head this would look like:

Prerequisites: Client K8s Pod is configured to use the proxy and up-and-running

Flow:
1. The tests container is started and starts the mockhttp standalone server
2. Client is opened in the browser and starts making request. These look like: https://env-<guid>.staging.domain.com
3. mockhttp server receives the requests and responds with a mock

Is this possible? Am I missing something?

Thank you!

**Comment by pimterry** [comment]
Absolutely! That's exactly what it's designed to do.

You need to:
* Start a proxy using Mockttp (maybe with HTTPS certificates, if you're using HTTPS)
* Start your app, configured to use that proxy (and configured to trust the HTTPS certificates, if using HTTPS)
* In the proxy server, match and mock the requests you want, like `mockttpServer.get("https://example.com").thenReply(200, "Mock response")`

There's a bunch more details in there of course, but give that a go and let me know if you have any questions or need any help.

**Comment by pimterry** [comment]
@Cosmin-Gramada I'm going to close this now, but feel free to get in touch if you're still having issues with this, or if you've got any questions.

**Comment by nderevjanik-skillz** [comment]
Similar question, can mockttp intercept and modify a response coming from the actual server?

For example I'd like to use the full JSON response from an actual REST API, but modify a portion of it prior to it being consumed by the client application.

**Comment by pimterry** [comment]
@nderevjanik-skillz yes, absolutely. You need to match the traffic you care about (perhaps all of it), then use `thenPassThrough` to proxy that traffic upstream, and use the `beforeResponse` callback to edit it. That callback is given every response that's proxied, and can return values to overwrite parts of it. For example:

```javascript
await server.anyRequest().thenPassThrough({
  beforeResponse: (response) => {
    const existingBody = response.body.json; // .json automatically parses existing JSON

    // Return whichever fields you want to overwrite: status, headers, body, etc.
    return {
      json: { // Returning .json, stringifies & sets application/json content-type automatically
        ...existingBody,
        fieldToOverwrite: 1234
      }      
    };
  }
});
```

There's some working examples in the tests too that might be of interest: https://github.com/httptoolkit/mockttp/blob/8f7ad95ec7f2a56068dc6f034647f46c35af72fb/test/integration/proxy.spec.ts#L398-L481. The Mockttp [API reference](https://httptoolkit.github.io/mockttp/interfaces/_mockttp_.mockttp.html) includes the nitty gritty details & explanations. If you have any questions at all, just let me know!

**Comment by nderevjanik-skillz** [comment]
I'm running into an issue overwriting the intercepted response. The client is not seeing the overwritten response, as if nothing changed.

Here's a code snippet:

```typescript
let responseHandler = (response: PassThroughResponse) => {
    const existingBody = response.body.json;
    console.log(existingBody);

    if (Array.isArray(existingBody)) {
        console.info('Stubbing response...')
        existingBody.push({ 'key': 'some.string.key', 'value': 'STUBBED!' });
    }

    return {
        json: existingBody
    }
};

driver.call(() => mockServer.get('/v1/settings').thenPassThrough({
    beforeResponse: responseHandler,
}));

driver.call(() => mockServer.anyRequest().thenPassThrough());
```

I can see "Stubbing response..." log messages and putting a breakpoint on the return shows the proper overwritten response.

I'm wondering if the last line: `mockServer.anyRequest().thenPassThrough()` is causing issues. However, without it the client crashes because none of the other requests are passed through.

FYI- `driver.call()` is a convention used by Webdriver.io. It's similar to async / await.

**Comment by pimterry** [comment]
Hi @nderevjanik-skillz. I suspect what's happening here is that it's working _once_, and then stopping. Does that sound plausible?

This will happen because both `anyRequest()` and `get('/v1/settings')` both match the request. If you have multiple rules for an incoming request, by default Mockttp will run them in order, for each incoming request. So the below code returns 1 for the first request, 2 for the second request, etc:

```javascript
mockServer.get('/abc').thenReply(200, '1');
mockServer.get('/abc').thenReply(200, '2');
mockServer.get('/abc').thenReply(200, '3');
```

Once all the matching rules have been run, the last rule repeats indefinitely: in your case, your /v1/settings rule will run once, then your anyRequest rule will run forever.

That's just the default though, and there are other options here. First, you could configure the first rule to _always_ run for matching traffic, with:

```javascript
mockServer.get('/v1/settings').always().thenPassThrough({ ...
```

`always()` ensures that the rule always runs if it matches. You can also use things like once, twice, `times(n)`, see the API docs for details: https://httptoolkit.github.io/mockttp/classes/_rules_mock_rule_builder_.mockrulebuilder.html#always

Alternatively, you could use a single anyRequests rule with a `beforeRequest` on all requests, and manually match and handle requests yourself there. I wouldn't advise that most of the time, but if you're finding your want complex direct control over how things work, that will work just fine. There will be a small performance hit if you're frequently streaming large request bodies, but probably not a measurable one in practice.

It's also possible there's some other bug here and I'm missing something, but I think the above is the most likely issue.

**Comment by pimterry** [comment]
> Also, I'm curious if I should really be using anyRequest().

Yep, I think it's a good use here. Mockttp doesn't pass through traffic by default, you need to explicitly opt into that, and using an anyRequest() rule to do so makes reasonable sense to me.

You could use more precisely targetted rules if you want to be sure your app-under-test isn't making unexpected API requests (e.g. only pass through certain hosts, or even specific endpoints) but up to you really, I don't think there's a clearly better answer there.

**Comment by pson-skillz** [comment]
sorry about the late response, I've re-ran through it with http filter and loopback interface:
[Archive 2.zip](https://github.com/httptoolkit/mockttp/files/7462696/Archive.2.zip)

**Comment by pimterry** [comment]
Hi @pson-skillz. Those PCAPs do contain HTTP traffic, but I still can't see the failures you're describing anywhere... There is no `/v1/user` request in there, which is the URL you used in your example above.

Can you point me at the successful & failing requests that you're talking about in those PCAPs?
