### ISSUE TITLE
Feature Request: Include request body in server events

### ISSUE THREAD

**Issue by Ivasan7** [httptoolkit/mockttp#43]
I would like to do some bit more complicated  things, maybe which are not intended but would be quite simple if on a request the body of the message would also be preserved. With `GET` was a bit easier to do but I was trying to something like:

```typescript

let a = [1,2,3]

function changeA(index: number, val: number) {
   a[index] = val;
}

await mockServer.post(/url).thenReply(200, 'OK');

mockServer.on('request-initiated', req => {
   // the req would be a JSON object where would be an index and a value
   changeA(request.body.index, request.body.value);  //Error: request.body is not there
}) 
```

**Comment by pimterry** [comment]
This is an easy fix I think: you want to use the `request` event, not `request-initiated`. See the docs here: https://httptoolkit.github.io/mockttp/interfaces/_mockttp_.mockttp.html#on.

`request-initiated` fires when the headers of the request are received, without waiting for the body. `request` fires when the full request is received, including the body. That's why the body is missing here.

Does that solve your issue?

**Comment by Ivasan7** [comment]
@pimterry ahh, makes sense, I will try it and if it works will close this. Thanks for the fast reply.

**Comment by Ivasan7** [comment]
@pimterry works like a charm. closing.
