### ISSUE TITLE
ERR_CONTENT_DECODING_FAILED when intercepting and modifying JSON responses

### ISSUE THREAD

**Issue by tiberiualex** [httptoolkit/mockttp#63]
Hi,

I'm trying to integrate Mockttp into a test suite, but changing the JSON response results in a network error in the browser, `ERR_CONTENT_DECODING_FAILED`. I've tried using both `body` with a string and `json` with an object to return a modified response, but neither seems to be working. Changing just the response status or the headers is working correctly. This is a snippet of the code:

```javascript
(async () => {
  const mockttp = require("mockttp");
  const chromeLauncher = require("chrome-launcher");

  const https = await mockttp.generateCACertificate();
  const server = mockttp.getLocal({ https });

  const loginError = '{"errors":[{"detail":"Invalid login details."}]}';

  server.anyRequest().thenPassThrough({
    beforeResponse: async (res) => {
      if (res.headers["content-type"] === "application/json;charset=utf-8") {
        const payload = await res.body.getJson();

        if (payload.access_token) {
          return {
            status: 403,
            body: loginError,
          };
        }

        return res;
      }

      return res;
    },
  });

  await server.start();

  const caFingerprint = mockttp.generateSPKIFingerprint(https.cert);
  console.log(`Server running on port ${server.port}`);
  console.log(`CA cert fingerprint ${caFingerprint}`);

  const chrome = await chromeLauncher.launch({
    chromeFlags: [
      "--window-size=1200,800",
      "--user-data-dir=/c/Users/path/to/profile",
      "--auto-open-devtools-for-tabs",
      `--proxy-server=localhost:${server.port}`,
      `--ignore-certificate-errors-spki-list=${caFingerprint}`,
    ],
  });
})();
```

**Comment by pimterry** [comment]
This usually means something odd is going on with your [content-encoding](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Encoding). What is the content-encoding header in your response?

**Comment by tiberiualex** [comment]
> This usually means something odd is going on with your [content-encoding](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Encoding). What is the content-encoding header in your response?

The content-encoding is gzip.

**Comment by pimterry** [comment]
Yes, OK. When you use a `beforeResponse` callback, Mockttp won't automatically handle encoding that body for you. That means that currently your code is returning a response header that tells the browser that your body is gzipped, but then the content isn't actually gzipped at all. The browser tries to un-gzip it, and fails, and that's where you see your error.

You have two options:
* You can drop the content-encoding header. This is quick & easy, so I'd try that first.
* If that doesn't work for your use case (e.g. some client always expects a gzipped response) then you can encode the body instead, so that it matches the header. You can use [the http-encoding package](https://www.npmjs.com/package/http-encoding) to do this very easily with something like: `encodedBody = await encodeBuffer(Buffer.from(loginError), res.headers['content-encoding'])`

This has been something that's caused confusion elsewhere too (see #61), and I'm open to improvements there, but automatically encoding a returned body here would be a breaking change, and it is useful to have the option to encode manually, to support unusual encodings or to test invalid responses.

**Comment by tiberiualex** [comment]
Thank you for the thorough explanation. Both options fix my problem. I will have a look at adding it as an option, hopefully I'm not out of my depth 😅

**Comment by pimterry** [comment]
This is now fixed in the just-released Mockttp v3. All callbacks, incuding beforeRequest and beforeResponse, will now automatically encode the returned body to match the final `content-encoding` of the request/response.

This is a breaking change (part of why it's v3), but you can get the old behaviour back by returning `rawBody` with a pre-encoded buffer instead of `body`/`json` in the callback. Raw bodies are sent as they are, with no encoding step. Thanks for filing this!
