### ISSUE TITLE
Unknown TLS error (tls_choose_sigalg: no suitable signature)

### ISSUE THREAD

**Issue by ghostlexly** [httptoolkit/mockttp#67]
I'am receiving this message when i'm trying to connect to http://connectivitycheck.gstatic.com/generate_204

![image](https://user-images.githubusercontent.com/62400734/148925115-31288c81-0ebd-4d90-8c8d-39a281df78e5.png)

**Comment by pimterry** [comment]
Hi @ghostlexly. That's unusual, but extra surprising because you don't need to be using TLS at all here - that's a plain HTTP address.

Can you share more information about how your setup works and what you're trying to do? Are you connecting to the proxy over TLS? Is your tunnelled connection using TLS?

You might be able to get more information by enabling debug mode - you can do that by initializing the server with `getLocal({ debug: true })`. That should report what connections Mockttp is seeing and what exactly it's trying to do.

**Comment by ghostlexly** [comment]
Hi @pimterry , my setup is:
Android Smartphone connecting to => Raspberry Pi (as wifi hotspot) => mockttp proxy

I was unable to get a wifi connection on my smartphone due to this issue.
i'll retry with debug: true and write the results here.

Thank you

**Comment by ghostlexly** [comment]
It's really strange but the issue disappeared after the add of the certificate  as a trusted certificate on the smartphone.
Looks like this error appears on HTTP connections if the certificate is not trusted and drop the connections.

**Comment by pimterry** [comment]
Ok, that makes sense! It's a surprising error for that (I'd definitely expect a certificate rejection of some form) but it's not completely out of character. That you're using TLS also makes sense in that case, since I'd expect Android to use TLS to set up the proxy connection in the first instance regardless of the final destination. Glad this is sorted :+1:
